---
title: "ex2.3_PCA"
output: pdf_document
---

---
title: "exercise2_group4_PCA"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(gmodels)
library(class)
library(caret)
library(swirl)
library(ggplot2)
library(spatstat)
```

## 2.3  Preprocessing


## Functions to plot the results

```{r}

# get accuracy of the labels in percents
get_accuracy <- function(predicted_labels, test_labels){
  # accuracy(table(numbers_test_pred,id_test_labels))
  tab <- table(predicted_labels, test_labels)
  sum(diag(tab)/(sum(rowSums(tab)))) * 100
}

knn_get_pca_plot_data <- function(test_data, test_labels, train_data, train_labels, repetitions = 10, k, searched_accum_var){
      
    test_time_v <- c()
    test_accuracy_v <- c()
    train_accuracy_v <- c()
    
    for (rep in c(1:repetitions)){
      t_start <- as.numeric(proc.time())
      # get the prediction
      numbers_test_pred <- knn(train = train_data, test = test_data, cl = train_labels, k=k)
      t_end <- as.numeric(proc.time())
      delta_t <- (t_end -  t_start)[3]  # seconds
      test_time_v <- c(test_time_v, delta_t)
      #print(test_time_v)
      
      # see the performance on testing data
      k_accuracy_test <-get_accuracy(test_labels, numbers_test_pred)
      test_accuracy_v <- c(test_accuracy_v, k_accuracy_test)
      
      # check the performance on testing data
      numbers_train_pred <- knn(train = train_data, test = train_data, cl = train_labels, k=k)
      k_accuracy_train <-get_accuracy(train_labels, numbers_train_pred)
      train_accuracy_v <- c(train_accuracy_v, k_accuracy_train)
    }
    
    return(list("searched_accum_var"=searched_accum_var, "k"=k,"test_time_v"=test_time_v, "test_accuracy_v"=test_accuracy_v, "train_accuracy_v"=train_accuracy_v))
}

# Plot all the results given the data
plot_results <- function(plot_data_ks_l){
  ks <- c()
  exec_time_means <- c()
  exec_time_stds <- c()
  
  test_accuracy_means <- c()
  test_accuracy_stds <- c()
  
  train_accuracy_means <- c()
  train_accuracy_stds <- c()
    
  for (plot_data_k in plot_data_ks_l){
    #print(plot_data_k$k)
    ks <- c(ks, plot_data_k$k)
    exec_time_means <- c(exec_time_means, mean(plot_data_k$test_time_v))
    exec_time_stds <- c(exec_time_stds, sd(plot_data_k$test_time_v))
    
    test_accuracy_means <- c(test_accuracy_means, mean(plot_data_k$test_accuracy_v))
    test_accuracy_stds <- c(test_accuracy_stds, sd(plot_data_k$test_accuracy_v))
    
    train_accuracy_means <- c(train_accuracy_means, mean(plot_data_k$train_accuracy_v))
    train_accuracy_stds <- c(train_accuracy_stds, sd(plot_data_k$train_accuracy_v))
  }
  df_plots <-data.frame(ks= ks, exec_time_means=exec_time_means, test_accuracy_stds=test_accuracy_stds)
  #print(head(df_plots))
  
  main <- paste("searched accummulated variance = ", plot_data_k$searched_accum_var, "%")
  
  g_time <- ggplot(df_plots, aes(x=ks)) + 
    geom_line(aes(y=exec_time_means)) + 
    geom_ribbon(aes(ymax=exec_time_means+exec_time_stds, ymin=exec_time_means-exec_time_stds), fill="pink", alpha=.5) +
    labs(title=main, 
         subtitle="execution time knn", 
         caption="Source: abcd", 
         y="time [ms]",
         x="k-number of nearest neighbours") 
  
  colors <- c("test data" = "darkgreen", "train data" = "darkblue" )
    g_accuracy <- ggplot(df_plots, aes(x=ks)) + 
    geom_line(aes(y=test_accuracy_means, color="test data")) + 
    geom_ribbon(aes(ymax=test_accuracy_means+test_accuracy_stds,
                    ymin=test_accuracy_means-test_accuracy_stds), fill="green", alpha=.5) +
    geom_line(aes(y=train_accuracy_means, color="train data")) + 
    geom_ribbon(aes(ymax=train_accuracy_means+train_accuracy_stds, ymin=train_accuracy_means-train_accuracy_stds), fill="blue", alpha=.5) +
  labs(title=main, 
         subtitle="accuracy comparison", 
         caption="Source: abcd", 
         y="accuracy [%]",
         x="k-number of nearest neighbours",
        color = "Legend") +
    scale_color_manual(values = colors)
  
  list_of_plots <- list(g_time, g_accuracy)
  
  return(list_of_plots)
}

```

## Min-Max Normalization Before PCA with Smoothing
``` {r}

# All persons in
load("../data/idList-co-100.Rdata")
id <- do.call(rbind, idList[1:10])
id <- as.data.frame(id)
id$V1 <- factor(id$V1)
# id - huge dataframe with everyone as TRAINING

##---------------------------------------------- Smoothing----------------------------
id_mat <- data.matrix(id, rownames.force = NA)
imageSize <- sqrt(ncol(id_mat) -1)
rotate <- function(x) t(apply(x, 2, rev))

smoothImage <- function(grayImg, sigma){
  smoothed <- as.matrix(blur(as.im(grayImg), sigma = sigma, normalise=FALSE, bleed = TRUE, varcov=NULL))
  return(smoothed)
}

for(i in 1:nrow(id_mat)){
  rotated <- c(id_mat[i,2:ncol(id)])
  image <- matrix(rotated,nrow = imageSize,ncol = imageSize, byrow = FALSE)
  image <- smoothImage(image,0.5)
  id_mat[i,2:ncol(id_mat)] <-matrix(image,nrow = 1,ncol = ncol(id_mat) -1, byrow = FALSE)
}

id <- as.data.frame(id_mat)
id[,1] <- factor(id[,1])

# Normalizing numeric data--------------------------------------------------------------

normalize <- function(x) {
  return((x-min(x))/ (max(x)- min(x)))
}

shuffle_df <- as.data.frame(lapply(id[,c(2:325)], normalize))

##Shuffling the data-------------------------------------------------------------------
set.seed(423)
shuffled_df <- id[sample(nrow(id)),]
accumulated_variance_v <- c(80) ## Karol said 80% fastest

#Split 50/50
test_rows_id <- 1:(nrow(shuffled_df)/2)
train_rows_id <- ((nrow(shuffled_df)/2) + 1) :nrow(shuffled_df)

##PCA------------------------------------------------------------------------------------
df_pca <- prcomp(x=shuffled_df[,(2:ncol(shuffled_df))], scale = TRUE, center = TRUE)

## Apply KNN with 10 fold Cross-Validation-----------------------------------------------

# for every fold check all the K's
ks <- c(1,17,29)
mse_k_all_folds_avg <- rep(0, length(ks)) # vector for storing error of each k 

# do the folds
folds <- createFolds(shuffled_df, k = 10)
fold_no <- 0 # just for printing the progress

#current fold - to ignore in training data but to use as a validation dataset: fold -> test!
for (fold in folds){
  fold_no <- fold_no + 1
        print(paste0("fold_no =", fold_no))
        
        fold <- sample(fold) # shuffle id numbers of fold 
        
        # use not-fold data as training and fold data as test
        not_f_df <- df_pca$x[ -fold, ] #training data
        f_df <- df_pca$x[ fold, ] #test data
        
        #not_f_df <- shuffled_df[ -fold, ] #training data
        #f_df <- shuffled_df[ fold, ] #test data
        
        # get labels - supervision part
        f_train_labels <- shuffled_df[,1]
        f_test_labels <- shuffled_df[,1]
  
  # predict with KNN - test all k's for each fold
  k_no <- 0 # just to keep track
  k_error <- 0
  plot_data_ks_l <- list()
        for (k in ks){
            k_no <- k_no + 1
            
            f_test_pred <- knn(train = not_f_df[,c(2:325)], test = f_df[,c(2:325)], cl = f_train_labels, k=k)
            
            print(paste0("      k =", k))
            plot_data <- knn_get_pca_plot_data(test_data=f_df, test_labels=f_test_labels,
                                               train_data=not_f_df, train_labels=f_train_labels,
                                               repetitions=10, k=k, searched_accum_var=searched_accum_var)
            #print(plot_data)
            plot_data_ks_l <- append(plot_data_ks_l, list(plot_data))
        }
  
  ## Plotting-----------------------------------------------------------------------------------
    list_of_plots <- plot_results(plot_data_ks_l)
    print(list_of_plots[1])
    print(list_of_plots[2])
    #show_pca_reconstruction(shuffled_df, searched_accum_var)
}

```

## Min-Max Normalization After PCA with Smoothing

```{r}

# All persons in
load("../data/idList-co-100.Rdata")
id <- do.call(rbind, idList[1:10])
id <- as.data.frame(id)
id$V1 <- factor(id$V1)
# id - huge dataframe with everyone as TRAINING

##---------------------------------------------- Smoothing----------------------------
id_mat <- data.matrix(id, rownames.force = NA)
imageSize <- sqrt(ncol(id_mat) -1)
rotate <- function(x) t(apply(x, 2, rev))

smoothImage <- function(grayImg, sigma){
  smoothed <- as.matrix(blur(as.im(grayImg), sigma = sigma, normalise=FALSE, bleed = TRUE, varcov=NULL))
  return(smoothed)
}

for(i in 1:nrow(id_mat)){
  rotated <- c(id_mat[i,2:ncol(id)])
  image <- matrix(rotated,nrow = imageSize,ncol = imageSize, byrow = FALSE)
  image <- smoothImage(image,0.5)
  id_mat[i,2:ncol(id_mat)] <-matrix(image,nrow = 1,ncol = ncol(id_mat) -1, byrow = FALSE)
}

id <- as.data.frame(id_mat)
id[,1] <- factor(id[,1])

##Shuffling the data-------------------------------------------------------------------
set.seed(423)
shuffled_df <- id[sample(nrow(id)),]
accumulated_variance_v <- c(80) ## Karol said 80% fastest

#Split 50/50
test_rows_id <- 1:(nrow(shuffled_df)/2)
train_rows_id <- ((nrow(shuffled_df)/2) + 1) :nrow(shuffled_df)

##PCA------------------------------------------------------------------------------------
df_pca <- prcomp(x=shuffled_df[,(2:ncol(shuffled_df))], scale = TRUE, center = TRUE)

# Normalizing numeric data--------------------------------------------------------------

normalize <- function(x) {
  return((x-min(x))/ (max(x)- min(x)))
}

shuffle_df <- as.data.frame(lapply(df_pca, normalize))

## Apply KNN with 10 fold Cross-Validation-----------------------------------------------

# for every fold check all the K's
ks <- c(1,17,29)
mse_k_all_folds_avg <- rep(0, length(ks)) # vector for storing error of each k 

# do the folds
folds <- createFolds(shuffled_df, k = 10)
fold_no <- 0 # just for printing the progress

#current fold - to ignore in training data but to use as a validation dataset: fold -> test!
for (fold in folds){
  fold_no <- fold_no + 1
        print(paste0("fold_no =", fold_no))
        
        fold <- sample(fold) # shuffle id numbers of fold 
        
        # use not-fold data as training and fold data as test
        not_f_df <- df_pca$x[ -fold, ] #training data
        f_df <- df_pca$x[ fold, ] #test data
        
        #not_f_df <- shuffled_df[ -fold, ] #training data
        #f_df <- shuffled_df[ fold, ] #test data
        
        # get labels - supervision part
        f_train_labels <- shuffled_df[train_rows_id, 1]
        f_test_labels <- shuffled_df[test_rows_id, 1]
  
  # predict with KNN - test all k's for each fold
  k_no <- 0 # just to keep track
  k_error <- 0
  plot_data_ks_l <- list()
        for (k in ks){
            k_no <- k_no + 1
            
            f_test_pred <- knn(train = not_f_df[,c(2:325)], test = f_df[,c(2:325)], cl = f_train_labels, k=k)
            
            print(paste0("      k =", k))
            plot_data <- knn_get_pca_plot_data(test_data=f_df, test_labels=f_test_labels,
                                               train_data=not_f_df, train_labels=f_train_labels,
                                               repetitions=10, k=k, searched_accum_var=searched_accum_var)
            #print(plot_data)
            plot_data_ks_l <- append(plot_data_ks_l, list(plot_data))
        }
  
  ## Plotting-----------------------------------------------------------------------------------
    list_of_plots <- plot_results(plot_data_ks_l)
    print(list_of_plots[1])
    print(list_of_plots[2])
    #show_pca_reconstruction(shuffled_df, searched_accum_var)
}
```




