---
title: "testing of the R functions"
output: pdf_document
---

```{r setup, include=FALSE}
library(gmodels)
library(class)
library(caret)
library(swirl)
library(ggplot2)
library(spatstat)
```


```{r test}

source("important_functions/load_data_id.R")
source("important_functions/get_training_test_data.R")

source("important_functions/get_normalized_data.R")
source("important_functions/get_gaussian_smoothed_data.R")
source("important_functions/view_data.R")

source("important_functions/get_k_clustered_cipher_data.R") 
source("important_functions/get_PCA_reduced_data.R") 


#loading data
id <- load_data_id(load_full=FALSE)
get_cipher_image(data=id, row_id=1640)

# normalizing
id_norm <- get_normalized_data(id)
get_cipher_image(data=id_norm, row_id=1640)

# gaussian smoothing
# id_smooth <- get_gaussian_smoothed_data(dataset=id, smooth_sigma=0.05)
# get_cipher_image(data=id_smooth, row_id=1640)



# PCA
pca_obj <- get_pca_obj(id_norm)
id_pca <- get_PCA_reduced_data(labels=id_norm$V1, pca_obj=pca_obj, searched_accum_var=85)
n_pcs <- ncol(id_pca) - 1  # minus label
show_pca_reconstruction(pca_obj, cipher=3, n_pcs=n_pcs)


id_pca <- prcomp(id_norm[,-1], center = TRUE, scale. = TRUE) 
eigs <- id_pca$sdev^2
Proportion = eigs/sum(eigs)
imageSize <- sqrt(ncol(id_norm) - 1)
# imageSize <- sqrt(ncol(id_mat) - 1)

for(cipherNumber in c(1640))
{
  # recreate using 90% of the data 
  trunc <- id_pca$x[cipherNumber,cumsum(Proportion) < 0.85] %*% t(id_pca$rotation[,cumsum(Proportion) < 0.85])
  
  trunc <- scale(trunc, center = -1 * id_pca$center, scale=FALSE)
  imageM <- matrix( trunc,nrow = imageSize,ncol = imageSize,byrow = FALSE)
  imageM <- rotate(imageM) # rotate is a function to rotate the image
  image( imageM, col=gray(0:100/100))
}



# # splitting data disjunct
# data_train_test_disjunct <- get_training_test_data_disjunct(data=id_norm)
# train_data_disjunct <- data_train_test_disjunct[[1]]
# test_data_disjunct <- data_train_test_disjunct[[2]]



# # splitting data all persons in
# data_train_test_allin <- get_training_test_data_allin(data=id_norm, training_percent=70)
# train_data_allin <- data_train_test_allin[[1]]
# test_data_allin <- data_train_test_allin[[2]]
# 
# # view random row
# get_cipher_image(data=train_data_allin, row_id=2)
# 
# # try k-means
# train_data_allin_kmeans <- get_k_clustered_cipher_data(data=train_data_allin_kmeans, n_cluster=1)
# get_cipher_image(data=train_data_allin_kmeans, row_id=1)




```
