---
title: "Exercise_3_clustering"
output: pdf_document
---

```{r setup, include=FALSE}
library(class)
library(caret)
```

```{r important functions}
load("data/idList-cor-100-2021new.Rdata") 

id <- do.call(rbind, idList[1:5]) # 5 person 
id <- as.data.frame(id)
id[,1] <- factor(id[,1])



get_normalized_data <- function(data){
  # normalize the image, but save the position of the label!
  library(dplyr)
  normalize <- function(x) {
  return ((x - min(x)) / (max(x) - min(x)))
  }
  
  id_sn <- as.data.frame(lapply(data[-1], normalize))
  
  id_labels <- data[,1]

  
  id_sn$V1 <- id_labels
  # id_sn[moveme(names(id_sn), "V1 first")]
  id_sn <- id_sn %>% select(V1, everything())
  return(id_sn)
}
tmp_normalized_dataset <- get_normalized_data(id)


get_k_clustered_cipher_data <- function(data, n_cluster){
  # for each digit 0-9 find all the rows and cluster them
  # what we get is the dataset with reduced amount of rows
  
  data <- id
  id_train_labels <- data[,1]
  cipher_cluster <- c()
  label_cluster <- c()
   for( i in 0:9) {
    data_cipher_i <- data[ id_train_labels == i, ]
    clusterData <- kmeans(data_cipher_i, n_cluster)
    cipher_cluster[[i + 1]] <- clusterData$centers
    label_cluster[[i + 1]] <- replicate(n_cluster, i)
  }
  
  train_lab <- factor(unlist(label_cluster))
  train_dat <- do.call(rbind, cipher_cluster)
  
  df = as.data.frame(train_dat)
  df <- df %>% select(V1, everything())
  return(df)
}
clustered_test_data <- get_k_clustered_cipher_data(data=id_test, n_cluster=100)

```

```{r test}

source("important_functions/load_data_id.R")
source("important_functions/get_normalized_data.R")
source("important_functions/get_training_test_data.R")
source("important_functions/view_data.R")
source("important_functions/get_k_clustered_cipher_data.R")


#loading data
id <- load_data_id()

# normalizing
id_norm <- get_normalized_data(id)

# gaussian smoothing
#TODO!

# splitting data disjunct
data_train_test_disjunct <- get_training_test_data_disjunct(data=id_norm)
train_data_disjunct <- data_train_test_disjunct[[1]]
test_data_disjunct <- data_train_test_disjunct[[2]]


# splitting data all persons in
data_train_test_allin <- get_training_test_data_allin(data=id_norm, training_percent=70)
train_data_allin <- data_train_test_allin[[1]]
test_data_allin <- data_train_test_allin[[2]]

# view random row
view_data(train_data_allin)



```
