---
title: "testing of the R functions"
output: pdf_document
---

```{r setup, include=FALSE}
library(class)
library(caret)
knitr::opts_chunk$set(echo = TRUE)
library("kernlab")
```


```{r test}

source("important_functions/load_data_id.R")
source("important_functions/get_normalized_data.R")
source("important_functions/get_training_test_data.R")
source("important_functions/view_data.R")

source("important_functions/get_k_clustered_cipher_data.R") # not yet tested

#loading data
id <- load_data_id()

# normalizing
id_norm <- get_normalized_data(id)

# gaussian smoothing
#TODO!

# splitting data disjunct
data_train_test_disjunct <- get_training_test_data_disjunct(data=id_norm)
train_data_disjunct <- data_train_test_disjunct[[1]]
test_data_disjunct <- data_train_test_disjunct[[2]]


# splitting data all persons in
data_train_test_allin <- get_training_test_data_allin(data=id_norm, training_percent=70)
train_data_allin <- data_train_test_allin[[1]]
test_data_allin <- data_train_test_allin[[2]]

# view random row
# view_data(train_data_allin)  # TODO

```


# LINEAR KERNEL - VANILLADOT
classifier_rbf <-ksvm(V1~ ., data = train_data_allin, kernel = "vanilladot", C = 0.5)
datasetTest <- predict(classifier_rbf,test_data_allin)
confusionMatrix(datasetTest, test_data_allin$V1)

<!-- #RADIAL BASIS KERNEL - RBFDOT -->
<!-- classifier_rbf <-ksvm(V1~., data = train, kernel = "rbfdot", kpar=list(sigma=0.05), C = 1) -->
<!-- datasetTest <- predict(classifier_rbf,test_data_allin) -->
<!-- confusionMatrix(datasetTest, test_data_allin$V1) -->









